### ISSUE TITLE
Ser väldigt bra ut

### ISSUE THREAD

**Issue by Hagmar** [Hagesjo/shrdlite#1]
Tänkte bara säga att allt ser bra ut hittills!

**Comment by hex6** [comment]
I have this issue as well,
`rm -rf .` usually solves it, but it didn't work this time for some reason.

**Comment by Hagmar** [comment]
Have you tried this? It's a small workaround
`alias cd='echo "TJENNA"'`

**Comment by hex6** [comment]
Don't understand instructions, sorry my computer is on fire.

**Comment by Hagmar** [comment]
Dick stuck in toaster

**Comment by Hagesjo** [comment]
This was fixed in the patch released innan jul, however, it is only available for those who aren't upside down. Closing as WFM.
